name: fabrica
base: core18
version: '0.8.1'
summary: Build snaps by simply pointing a web form to a git tree
description: |
  Fabrica is a web service to be run on an lxd appliance. It spawns a
  web ui that allows you to point to cloneable git trees, initializes
  lxd and builds snap packages of the provided source trees.

grade: stable
confinement: strict

apps:
  init:
    command: bin/init.py
    daemon: simple
    plugs:
      - lxd
      - mount-observe
      - network-bind
  build:
    command: bin/build.py
    plugs:
      - lxd
      - mount-observe
      - network
      - network-bind
      - system-observe
  web:
    command: bin/web
    daemon: simple
    plugs:
      - lxd
      - mount-observe
      - network
      - network-bind
      - system-observe
  watch:
    command: bin/watch
    daemon: simple
    plugs:
      - lxd
      - mount-observe
      - network
      - network-bind
      - system-observe

parts:
  pylxd:
    plugin: python
    python-packages:
      - pylxd
    build-packages:
      - libffi-dev
      - libssl-dev
  scripts:
    source: .
    plugin: nil
    override-build: |
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp bin/init.py $SNAPCRAFT_PART_INSTALL/bin/
      cp bin/build.py $SNAPCRAFT_PART_INSTALL/bin/
    stage-packages:
      - python3-websockets

  application:
    plugin: go
    source: .
    source-type: git
    build-packages:
      - gcc
    stage-packages:
      - git
      - libcurl4-openssl-dev

  bin:
    source: snap/local
    plugin: dump
    organize:
      "*": /bin/
