#! /bin/sh


if [ ! -f "$SNAP_DATA/ssh/ssh_host_rsa_key" ]; then
  echo "generate ssh host keys"
  mkdir -p $SNAP_DATA/ssh
  cp $SNAP/ssh/* $SNAP_DATA/ssh/
  $SNAP/bin/fabrica -mode keygen
fi

if ! snapctl is-connected mount-observe; then
  echo "also need read access to disk size information !!!"
  echo "please run 'snap connect ${SNAP_NAME}:mount-observe"
  echo
  echo "keeping service disabled for the moment"
  exit 0
fi

if snapctl services ${SNAP_NAME}.init | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.init 2>&1 || true
fi

