#! /bin/sh

if ! snapctl is-connected lxd; then
  echo "also need write access to lxd socket !!!"
  echo "please run 'snap connect ${SNAP_NAME}:lxd lxd:lxd"
  echo
  echo "keeping service disabled for the moment"
  exit 0
fi

if snapctl services ${SNAP_NAME}.init | grep -q inactive; then
  snapctl start --enable ${SNAP_NAME}.init 2>&1 || true
fi
